pipeline{
    agent any
    stages{
        stage('Deploy as a task'){
            environment {
                AWS_CREDENTIALS = credentials('aws-creds')
            }
            steps{
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', 
                                  credentialsId: 'aws-creds',
                                  accessKeyVariable: 'AWS_ACCESS_KEY_ID', 
                                  secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]){
                echo "tsak deploy very soon"
                sh "chmod +x ./create_service.sh"
                sh "./create_service.sh"
                echo "are we done"
                echo "we are so cooked"
                }
            }
        }
    }
}